# Generated by Django 3.0.5 on 2020-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.CharField(default='64125', max_length=10),
            preserve_default=False,
        ),
    ]
