# Generated by Django 3.0.5 on 2020-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20200430_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='pics'),
        ),
    ]
