# Generated by Django 3.0.5 on 2020-04-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TouriztoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='itenary',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TouriztoApp.Destination')),
            ],
        ),
    ]
