# Generated by Django 3.0.5 on 2020-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TouriztoApp', '0002_auto_20200428_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
