# Generated by Django 3.0.5 on 2020-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TouriztoApp', '0005_auto_20200429_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
