# Generated by Django 3.0.5 on 2020-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TouriztoApp', '0006_destination_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(default='Travel', max_length=100),
            preserve_default=False,
        ),
    ]
