# Generated by Django 3.0.5 on 2020-05-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TouriztoApp', '0007_destination_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='category',
        ),
    ]
