# Generated by Django 3.0.5 on 2020-04-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travelouge', '0002_auto_20200428_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travelouge.Blog')),
            ],
        ),
    ]
